#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#f291e2
bspc config normal_border_color \#0e1419

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
sxhkdrc &
picom &
# nitrogen --restore &
# lxappearance &
$HOME/.config/awesome/spolybar.sh &
$HOME/.config/awesome/bg-script.sh &
xsetroot -cursor_name left_ptr &
# export GTK2_RC_FILES="$HOME/.gtkrc-2.0" &
